// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qHOen6SKTh_VYk16VOZ_cCDLj81Knp8',
    appId: '1:63934633031:android:da82a3b0fcde24b882cd62',
    messagingSenderId: '63934633031',
    projectId: 'audioboyscall-1',
    storageBucket: 'audioboyscall-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8g34jtVGto5GvRQn7qePZ8hNVMVM6Qk',
    appId: '1:63934633031:ios:6ee44aca1b8bfe0282cd62',
    messagingSenderId: '63934633031',
    projectId: 'audioboyscall-1',
    storageBucket: 'audioboyscall-1.firebasestorage.app',
    iosBundleId: 'com.lovecall.loveCallBoys',
  );
}
